.TH "product_release_main_page" 3 "Sun Jan 17 2016" "Version x.x.x" "project_template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
product_release_main_page \- Release Notes: 
Foreword: provide brief description
.PP
This product release document is divided in the following sections:
.IP "\(bu" 2
\fBIntroduction\fP
.IP "\(bu" 2
\fBRequirements\fP
.IP "\(bu" 2
\fBHardware Design\fP
.IP "\(bu" 2
\fBSoftware Design\fP
.PP
.PP
For details on source code and related documentation visit respective section\&. 
