.TH "software_design" 3 "Sun Jan 17 2016" "Version x.x.x" "project_template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
software_design \- Software Design 
provide brief details for this section\&.
.SH "Section 01"
.PP
Image: titleTo load an image set the parameter IMAGE_PATH to appropriate folder in doxyfile for the project
.SS "Subsction 01"
provide details
.IP "\(bu" 2
\fBSection 02\fP Section 02
.IP "\(bu" 2
\fBSection 03\fP Section 03
.PP
.SS "sw_subsection_02"
Table Column 1 Column 2 Details  Details Details Details Details Details Details Details Details Details 
.PP
Go to \fBTop\fP / \fBRelease Note:Main Menu\fP\&.
.PP

.br

.br
.SH "Section 02"
.PP
Image: titleTo load an image set the parameter IMAGE_PATH to appropriate folder in doxyfile for the project
.SS "Subsection 04"

.br
Go to \fBTop\fP / \fBRelease Note:Main Menu\fP\&.
.PP

.br
 
.br
.SH "Section 03"
.PP
.SS "Subsection 05"
Go to \fBTop\fP / \fBRelease Note:Main Menu\fP\&. 
