.TH "include/template.h" 3 "Sun Jan 17 2016" "Version x.x.x" "project_template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/template.h \- Provide short summary on function and the contents of file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMACRO_HF\fP   000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBentry_point_function_one\fP (int parameter_one, float parameter_two, char *parameter_three, float parameter_four, int parameter_five)"
.br
.RI "\fIProvide short description on functionality of function\&. \fP"
.ti -1c
.RI "void \fBentry_point_function_two\fP (int parameter_one, float parameter_two, char *parameter_three)"
.br
.RI "\fIProvide short description on functionality of function\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBglobal_variable_hf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide short summary on function and the contents of file\&. 


.PP
\fBAuthor:\fP
.RS 4
provide author details 
.RE
.PP
\fBDate:\fP
.RS 4
provide date
.RE
.PP
Provide detailed description 
.PP
Definition in file \fBtemplate\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MACRO_HF   000"
Provide description for documentation purpose 
.PP
Definition at line 68 of file template\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void entry_point_function_one (int parameter_one, float parameter_two, char * parameter_three, float parameter_four, int parameter_five)"

.PP
Provide short description on functionality of function\&. Provide detailed description of function, including calling mechanism and return value\&.
.IP "\(bu" 2
Functions
.IP "  1." 6
Function \&.\&.\&.1
.IP "  2." 6
Function \&.\&.\&.2
.IP "  3." 6
Function \&.\&.\&.3
.PP

.PP
.PP
\fBParameters:\fP
.RS 4
\fIparameter_one\fP Provide description 
.br
\fIparameter_two\fP Provide description 
.br
\fIparameter_three\fP Provide description 
.br
\fIparameter_four\fP Provide description 
.br
\fIparameter_five\fP Provide description 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 156 of file template\&.c\&.
.SS "void entry_point_function_two (int parameter_one, float parameter_two, char * parameter_three)"

.PP
Provide short description on functionality of function\&. Provide detailed description of function, including calling mechanism and return value\&.
.PP
\fBParameters:\fP
.RS 4
\fIparameter_one\fP Provide description 
.br
\fIparameter_two\fP Provide description 
.br
\fIparameter_three\fP Provide description 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 172 of file template\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int global_variable_hf"
Provide description for documentation purpose 
.PP
Definition at line 85 of file template\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for project_template from the source code\&.
