.TH "template.c" 3 "Sun Jan 17 2016" "Version x.x.x" "project_template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
template.c \- Provide short summary on function and the contents of file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'template\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'avr/io\&.h'\fP
.br
\fC#include 'avr/interrupt\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMACRO_SF\fP   999"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "\fIMain entry point for the program\&. Provide short description\&. \fP"
.ti -1c
.RI "void \fBentry_point_function_one\fP (int parameter_one, float parameter_two, char *parameter_three, float parameter_four, int parameter_five)"
.br
.RI "\fIProvide short description on functionality of function\&. \fP"
.ti -1c
.RI "void \fBentry_point_function_two\fP (int parameter_one, float parameter_two, char *parameter_three)"
.br
.RI "\fIProvide short description on functionality of function\&. \fP"
.ti -1c
.RI "float \fBlocal_function_one\fP (int parameter_one, float parameter_two, char *parameter_three)"
.br
.RI "\fIProvide short description on functionality of function\&. \fP"
.ti -1c
.RI "float \fBlocal_function_two\fP (int parameter_one, float parameter_two, char *parameter_three, float parameter_four, int parameter_five)"
.br
.RI "\fIProvide short description on functionality of function\&. \fP"
.ti -1c
.RI "\fBISR\fP (INT4_vect, ISR_BLOCK)"
.br
.RI "\fIProvide short description on interrupt service routine\&. \fP"
.ti -1c
.RI "\fBISR\fP (USART0_RX_vect, ISR_BLOCK)"
.br
.RI "\fIProvide short description on interrupt service routine\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBglobal_variable_sf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide short summary on function and the contents of file\&. 


.PP
\fBAuthor:\fP
.RS 4
provide author details 
.RE
.PP
\fBDate:\fP
.RS 4
provide date
.RE
.PP
Provide detailed description 
.PP
Definition in file \fBtemplate\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MACRO_SF   999"
Provide description for documentation purpose 
.PP
Definition at line 60 of file template\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void entry_point_function_one (int parameter_one, float parameter_two, char * parameter_three, float parameter_four, int parameter_five)"

.PP
Provide short description on functionality of function\&. Provide detailed description of function, including calling mechanism and return value\&.
.IP "\(bu" 2
Functions
.IP "  1." 6
Function \&.\&.\&.1
.IP "  2." 6
Function \&.\&.\&.2
.IP "  3." 6
Function \&.\&.\&.3
.PP

.PP
.PP
\fBParameters:\fP
.RS 4
\fIparameter_one\fP Provide description 
.br
\fIparameter_two\fP Provide description 
.br
\fIparameter_three\fP Provide description 
.br
\fIparameter_four\fP Provide description 
.br
\fIparameter_five\fP Provide description 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 156 of file template\&.c\&.
.SS "void entry_point_function_two (int parameter_one, float parameter_two, char * parameter_three)"

.PP
Provide short description on functionality of function\&. Provide detailed description of function, including calling mechanism and return value\&.
.PP
\fBParameters:\fP
.RS 4
\fIparameter_one\fP Provide description 
.br
\fIparameter_two\fP Provide description 
.br
\fIparameter_three\fP Provide description 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 172 of file template\&.c\&.
.SS "ISR (INT4_vect, ISR_BLOCK)"

.PP
Provide short description on interrupt service routine\&. Provide detailed description of interrupt service routine 
.PP
Definition at line 232 of file template\&.c\&.
.SS "ISR (USART0_RX_vect, ISR_BLOCK)"

.PP
Provide short description on interrupt service routine\&. Provide detailed description of interrupt service routine 
.PP
Definition at line 248 of file template\&.c\&.
.SS "float local_function_one (int parameter_one, float parameter_two, char * parameter_three)"

.PP
Provide short description on functionality of function\&. Provide detailed description of function
.PP
\fBParameters:\fP
.RS 4
\fIparameter_one\fP Provide description 
.br
\fIparameter_two\fP Provide description 
.br
\fIparameter_three\fP Provide description 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 193 of file template\&.c\&.
.SS "float local_function_two (int parameter_one, float parameter_two, char * parameter_three, float parameter_four, int parameter_five)"

.PP
Provide short description on functionality of function\&. Provide detailed description of function
.PP
\fBParameters:\fP
.RS 4
\fIparameter_one\fP Provide description 
.br
\fIparameter_two\fP Provide description 
.br
\fIparameter_three\fP Provide description 
.br
\fIparameter_four\fP Provide description 
.br
\fIparameter_five\fP Provide description 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 212 of file template\&.c\&.
.SS "int main (void)"

.PP
Main entry point for the program\&. Provide short description\&. Provide detailed description on the functionality of program and other related points\&. 
.PP
\fBNote:\fP
.RS 4
\fBmain()\fP function can be only appear in one module, which is the main entry point of program; hence remove it while coding a supporting module, which itself is not suppose to execute\&.
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 110 of file template\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int global_variable_sf"
Provide description for documentation purpose 
.PP
Definition at line 82 of file template\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for project_template from the source code\&.
